export enum CustomerStates {
    INIT,
    CALCULATING_WANDERING_TARGET,
    MOVING_TO_WANDER_TARGETR,
    LOOKIGN_FOR_PURCHASE_TARGET,
    CALCULATING_PATH_TO_PURCHASE,
    GOING_TO_PURCHASE,
    WAIT_FOR_PURCHASE,
    PURCHASING,
    LOOKIGN_FOR_LEAVE_TARGET,
    CALCULATING_LEAVING_PATH,
    LEAVING,
    LEAVE_IN_PROGRESS
}
