export enum Depths {
    UNDER_PLAYER,
    CHARACTER_UNDER_DESK,
    SHELF_UNDER_PLAYER,
    SELL_DESK,
    CHARACTER_ABOVE_DESK,
    CHARACTER_UNDER_SHELF,
    SHELF,
    CHARACTER_ABOVE_SHELF,
    ENTRANCE_DOOR,
    CEILING_LAMPS_LIGHTS,
    CEILING_LAMPS,
    FLY_TEXT,
    GRID_DEBUG,
    UI_ICONS,
    UI_DEBUG,
    UI
}
