export enum Depths {
    UNDER_PLAYER,
    CHARACTER_UNDER_DESK,
    SELL_DESK,
    CHARACTER_ABOVE_DESK,
    CHARACTER_UNDER_SHELF,
    DOWN_SHELF,
    CHARACTER_ABOVE_SHELF,
    ENTRANCE_DOOR,
    CEILING_LAMPS_LIGHTS,
    CEILING_LAMPS,
    FLY_TEXT,
    GRID_DEBUG
}
